fixing again cmake_run

diff --git a/cmake_run b/cmake_run
--- a/cmake_run
+++ b/cmake_run
@@ -1,31 +1,51 @@
 #!/bin/bash
 
 if [ -z "$CC" ]; then
+
    CC=gcc
+
+   if [ -n "`which gcc-6`" ]; then
+      CC=gcc-6
+   fi
 fi
 
 if [ -z "$CXX" ]; then
+
    CXX=g++
+
+   if [ -n "`which g++-6`" ]; then
+      CXX=g++-6
+   fi
 fi
 
-sed_ver_regex='s/[A-Za-z0-9+]+[ ].+[ ]([0-9]+[.][0-9]+[.][0-9]+)[ ].*/\1/g'
 
-cc_ver=`$CC --version | head -1 | sed -E "$sed_ver_regex"`
-cxx_ver=`$CXX --version | head -1 | sed -E "$sed_ver_regex"`
+if [ -z "`which $CC`" ]; then
+   echo "CC compiler '$CC' not found."
+   exit 1
+fi
 
-echo "CC version:  $cc_ver"
-echo "CXX version: $cxx_ver"
+if [ -z "`which $CXX`" ]; then
+   echo "CXX compiler '$CXX' not found."
+   exit 1
+fi
+
+
+cc_ver=`$CC --version | head -1 | grep -Eo '[0-9]+[.][0-9][.][0-9]+' | head -1`
+cxx_ver=`$CXX --version | head -1 | grep -Eo '[0-9]+[.][0-9][.][0-9]+' | head -1`
+
+echo "gcc version: $cc_ver"
+echo "g++ version: $cxx_ver"
 
 cc_major=`echo -ne $cc_ver | grep -Eo '[0-9]+' | head -1`
 cxx_major=`echo -ne $cxx_ver | grep -Eo '[0-9]+' | head -1`
 
 if [ $cc_major -lt 6 ]; then
-   echo "Your GCC compiler is too old. Version >= 6 is required."
+   echo "Your gcc compiler is too old. Version >= 6 is required."
    exit 1
 fi
 
 if [ $cxx_major -lt 6 ]; then
-   echo "Your G++ compiler is too old. Version >= 6 is required."
+   echo "Your g++ compiler is too old. Version >= 6 is required."
    exit 1
 fi
 
