[scripts] Check in build_fatpart for paths with whitespaces (#184)
As explained in issue #184 amd issue #159, Tilck's build system does not
support any paths with whitespaces because that will require a significant
amount of extra escaping everywhere, making the code much harder to read.
In addition to that, ad-hoc testing will be required to make sure that the new
case is fully supported in all the build configurations, with all the build
options and that we never break that feature in the future. The return on
investment for such a feature seems very low compared to the benefits, and
therefore, for the being being it won't be supported.

This simply change adds a check in the `build_fatpart` script for paths with
whitespaces and makes the build to fail gracefully in such a case.

diff --git a/scripts/templates/build_fatpart b/scripts/templates/build_fatpart
--- a/scripts/templates/build_fatpart
+++ b/scripts/templates/build_fatpart
@@ -77,8 +77,29 @@ function format_fatpart {
 }
 
 function create_sysroot_skeleton {
+
+   # Remove the sysroot directory created by the previous build
    rm -rf $bdir/sysroot
+
+   # Check if the sysroot directory contains any paths with whitespaces,
+   # because we don't support that and it's better to fail with a graceful
+   # error, in case someone places such a file/directory there.
+   if [ -n "$(find $maindir/sysroot -name "* *")" ]; then
+      echo "-----------------------------------------------------------------"
+      echo "ERROR: $maindir/sysroot contains paths with whitespaces "
+      echo "ERROR: and that is not supported. Here's the list of such paths:"
+      echo
+      find $maindir/sysroot -name "* *"
+      echo "-----------------------------------------------------------------"
+      exit 1
+   fi
+
+   # Copy our skeleton sysroot/ directory to the configured build directory
+   # so that in the next steps we can fill it with build-generated artifacts
+   # like binaries and libraries.
    cp -r $maindir/sysroot $bdir/
+
+   # Enter in the temporary sysroot directory for this build
    cd $bdir/sysroot
 
    # Remove the README file that is not supposed to be in the actual sysroot
