[codecov] Report coverage data to codecov just once

diff --git a/scripts/templates/generate_coverage_report b/scripts/templates/generate_coverage_report
--- a/scripts/templates/generate_coverage_report
+++ b/scripts/templates/generate_coverage_report
@@ -32,13 +32,12 @@ if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "                      DISCARDING any previous coverage.info data, "
    echo "                      producing a converage.info file"
    echo
-   echo "      --codecov       collect coverage info from the *.gcda files"
-   echo "                      DISCARDING any previous coverage.info data and"
-   echo "                      upload the data to CodeCov"
-   echo
    echo "      --acc           collect coverage info WITHOUT DISCARDING the"
    echo "                      previous converage.info data, producing a new"
    echo "                      converage.info file"
+   echo
+   echo "      --codecov       only upload the coverage data to CodeCov "
+   echo "                      assuming that 'coverage.info' exists"
    echo
    echo "      --gen           only generate html coverage output assuming that"
    echo "                      the file 'converage.info' exists"
@@ -79,6 +78,23 @@ if [[ "$1" == "--gen" ]]; then
    exit 0
 fi
 
+if [[ "$1" == "--codecov" ]]; then
+
+   if [ ! -f coverage.info ]; then
+      echo "ERROR: the file coverage.info does NOT exist."
+      exit 1
+   fi
+
+   if [[ "$CODECOV_TOKEN" == "" ]]; then
+      echo "No CODECOV_TOKEN defined. Unable to upload data to CodeCov"
+      exit 1
+   fi
+
+   # Upload report to CodeCov
+   bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
+   exit 0
+fi
+
 
 gcda_count=$(find . -name '*.gcda' | wc -l)
 if [[ $gcda_count == 0 ]]; then
@@ -107,11 +123,6 @@ fi
 
 # Keep only coverage.info
 rm -f lcov.info lcov2.info
-
-if [[ "$1" == "--codecov" ]]; then
-   # Upload report to CodeCov
-   bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
-fi
 
 # Remove all the coverage data files generated by the current run
 find . -type f -name '*.gcda' -print | xargs /bin/rm -f
