[kgcov] Dump of coverage data from the devshell works

diff --git a/scripts/templates/generate_coverage_report b/scripts/templates/generate_coverage_report
--- a/scripts/templates/generate_coverage_report
+++ b/scripts/templates/generate_coverage_report
@@ -29,17 +29,19 @@ if [[ "$1" == "-h" || "$1" == "--help" ]]; then
 
    echo "Usage:"
    echo "      <no options>    collect coverage info from the *.gcda files "
-   echo "                      DISCARDING any previous coverage.info data"
+   echo "                      DISCARDING any previous coverage.info data, "
+   echo "                      producing a converage.info file"
    echo
    echo "      --codecov       collect coverage info from the *.gcda files"
    echo "                      DISCARDING any previous coverage.info data and"
-   echo "                      update the data to CodeCov"
+   echo "                      upload the data to CodeCov"
    echo
    echo "      --acc           collect coverage info WITHOUT DISCARDING the"
-   echo "                      previous converage.info data"
+   echo "                      previous converage.info data, producing a new"
+   echo "                      converage.info file"
    echo
    echo "      --gen           only generate html coverage output assuming that"
-   echo "                      converage.info exists"
+   echo "                      the file 'converage.info' exists"
    echo
    echo "      --info          show configuration info"
    echo "      --help          show this help message"
@@ -57,12 +59,6 @@ fi
 
 cd "$BUILD"
 echo "NOTE: Use '$GCOV' as gcov tool"
-
-gcda_count=$(find . -name '*.gcda' | wc -l)
-if [[ $gcda_count == 0 ]]; then
-   echo "ERROR: no gcda files found in $BUILD"
-   exit 1
-fi
 
 function gen_html_coverage {
 
@@ -82,6 +78,14 @@ if [[ "$1" == "--gen" ]]; then
    gen_html_coverage
    exit 0
 fi
+
+
+gcda_count=$(find . -name '*.gcda' | wc -l)
+if [[ $gcda_count == 0 ]]; then
+   echo "ERROR: no gcda files found in $BUILD"
+   exit 1
+fi
+
 
 if [[ "$1" != "--acc" ]]; then
    rm -f lcov*.info
