[scripts] Improving generate_coverage_report

diff --git a/scripts/templates/generate_coverage_report b/scripts/templates/generate_coverage_report
--- a/scripts/templates/generate_coverage_report
+++ b/scripts/templates/generate_coverage_report
@@ -22,18 +22,67 @@ BUILD="@CMAKE_BINARY_DIR@"
 HTML_DIR="@COVERAGE_HTML_DIR@"
 GCOV="@TOOL_GCOV@"
 
-# Sets $GCOV
-echo "NOTE: Use '$GCOV' as gcov tool"
-
 LCOV="$TC/lcov/bin/lcov"
 GENHTML="$TC/lcov/bin/genhtml"
 
+if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+
+   echo "Usage:"
+   echo "      <no options>    collect coverage info from the *.gcda files "
+   echo "                      discarding any previous coverage.info data and "
+   echo "                      generate html coverage"
+   echo
+   echo "      --codecov       collect coverage info from the *.gcda files "
+   echo "                      discarding any previous coverage.info data and "
+   echo "                      update the data to CodeCov"
+   echo
+   echo "      --acc           collect coverage info and generate html coverage"
+   echo "                      without discarding the previous converage.info "
+   echo "                      data"
+   echo
+   echo "      --gen           only generate html coverage output assuming that"
+   echo "                      converage.info exists"
+   echo
+   echo "      --info          show configuration info"
+   echo "      --help          show this help message"
+   exit 0
+fi
+
+if [[ "$1" == "--info" ]]; then
+   echo "GCOV:       $GCOV"
+   echo "LCOV:       $LCOV"
+   echo "GENHTML:    $GENHTML"
+   echo "BUILD_DIR:  $BUILD"
+   echo "HTML_DIR:   $HTML_DIR"
+   exit 0
+fi
+
 cd "$BUILD"
+echo "NOTE: Use '$GCOV' as gcov tool"
 
 gcda_count=$(find . -name '*.gcda' | wc -l)
 if [[ $gcda_count == 0 ]]; then
    echo "ERROR: no gcda files found in $BUILD"
    exit 1
+fi
+
+function gen_html_coverage {
+
+   if [ ! -f coverage.info ]; then
+      echo "ERROR: the file coverage.info does NOT exist."
+      exit 1
+   fi
+
+   # (Eventually) remove and create the output coverage directory
+   rm -rf "$HTML_DIR"; mkdir -p "$HTML_DIR"
+
+   # Generate the HTML coverage output
+   $GENHTML --output-directory "$HTML_DIR" coverage.info
+}
+
+if [[ "$1" == "--gen" ]]; then
+   gen_html_coverage
+   exit 0
 fi
 
 if [[ "$1" != "--acc" ]]; then
@@ -54,22 +103,17 @@ else
    mv merged.info coverage.info
 fi
 
-if [[ "$1" == "--codecov" ]]; then
+# Keep only coverage.info
+rm -f lcov.info lcov2.info
 
-   $LCOV --list coverage.info
+if [[ "$1" == "--codecov" ]]; then
 
    # Upload report to CodeCov
    bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
 
 else
-
-   # (Eventually) remove and create the output coverage directory
-   rm -rf "$HTML_DIR"; mkdir -p "$HTML_DIR"
-
-   # Generate the HTML coverage output
-   $GENHTML --output-directory "$HTML_DIR" coverage.info
+   gen_html_coverage
 fi
 
 # Remove all the coverage data files generated by the current run
 find . -type f -name '*.gcda' -print | xargs /bin/rm -f
-
