[toolchain] More refactoring 2
In this change, more functions from the big `build_toolchain` are extracted
to dedicated functions placed in dedicated files.

diff --git a/scripts/bash_includes/arch_utils b/scripts/bash_includes/arch_utils
--- a/scripts/bash_includes/arch_utils
+++ b/scripts/bash_includes/arch_utils
@@ -16,6 +16,15 @@ function get_efi_arch {
    echo "$ret"
 }
 
+function set_arch_gcc_tc_arch {
+   case $1 in
+      i386) ARCH_GCC_TC="i686";;
+      x86_64) ARCH_GCC_TC="x86_64";;
+      riscv64) ARCH_GCC_TC="riscv64";;
+      *) echo "Architecture '$1' not supported."; exit 1;;
+   esac
+}
+
 function set_host_arch_variable {
    HOST_ARCH="`uname -m`"
 
@@ -53,45 +62,60 @@ function set_host_arch_variable {
 
 function set_arch_variables {
 
-   if [[ "$1" == "i386" ]]; then
+   case $1 in
+      i386)
+         ARCH_SHORT="x86"
+         ARCH_FAMILY="generic_x86"
+         ARCH_ELF_NAME="elf32-i386"
+         ARCH_LD_OUTPUT="elf_i386"
+         ARCH_EFI=$(get_efi_arch $ARCH)
+         ARCH_GCC_TC="i686"
+         ARCH_GCC_FLAGS="-m32 -march=$ARCH_GCC_TC"
+         ARCH_GCC_TC_CODENAME="x86-i686"
+      ;;
 
-      ARCH_SHORT="x86"
-      ARCH_FAMILY="generic_x86"
-      ARCH_ELF_NAME="elf32-i386"
-      ARCH_LD_OUTPUT="elf_i386"
-      ARCH_EFI=$(get_efi_arch $ARCH)
-      ARCH_GCC_TC="i686"
-      ARCH_GCC_FLAGS="-m32 -march=$ARCH_GCC_TC"
-      ARCH_GCC_TC_CODENAME="x86-i686"
+      x86_64)
+         ARCH_SHORT="x86_64"
+         ARCH_FAMILY="generic_x86"
+         ARCH_ELF_NAME="elf64-x86-64"
+         ARCH_LD_OUTPUT="elf_x86_64"
+         ARCH_EFI=$(get_efi_arch $ARCH)
+         ARCH_GCC_TC="x86_64"
+         ARCH_GCC_FLAGS="-m64"
+         ARCH_GCC_TC_CODENAME="x86-64-core-i7"
+      ;;
 
-   elif [[ "$1" == "x86_64" ]]; then
+      riscv64)
+         ARCH_SHORT="riscv64"
+         ARCH_FAMILY="riscv"
+         ARCH_ELF_NAME="elf64-littleriscv"
+         ARCH_LD_OUTPUT="elf64lriscv"
+         ARCH_GCC_TC="riscv64"
+         ARCH_GCC_FLAGS=""
+         ARCH_GCC_TC_CODENAME="riscv64-lp64d"
+      ;;
 
-      ARCH_SHORT="x86_64"
-      ARCH_FAMILY="generic_x86"
-      ARCH_ELF_NAME="elf64-x86-64"
-      ARCH_LD_OUTPUT="elf_x86_64"
-      ARCH_EFI=$(get_efi_arch $ARCH)
-      ARCH_GCC_TC="x86_64"
-      ARCH_GCC_FLAGS="-m64"
-      ARCH_GCC_TC_CODENAME="x86-64-core-i7"
-
-   elif [[ "$1" == "riscv64" ]]; then
-
-      ARCH_SHORT="riscv64"
-      ARCH_FAMILY="riscv"
-      ARCH_ELF_NAME="elf64-littleriscv"
-      ARCH_LD_OUTPUT="elf64lriscv"
-      ARCH_GCC_TC="riscv64"
-      ARCH_GCC_FLAGS=""
-      ARCH_GCC_TC_CODENAME="riscv64-lp64d"
-
-   else
-      echo "Architecture '$1' not supported."
-      exit 1
-   fi
+      *)
+         echo "Architecture '$1' not supported."
+         exit 1
+      ;;
+   esac
 }
 
+#
+# If $ARCH_GCC_TC_VER has not been set externally or by the check above,
+# we'll use the pre-built bootlin toolchains, which do not use the GCC
+# version in their name, but a year/month combination with additional
+# fields. Therefore, let's map our desired GCC version to the bootlin
+# toolchain name.
+#
 function set_arch_gcc_tc_ver {
+
+   if [[ "$ARCH_GCC_TC_VER" != "" ]]; then
+      # ARCH_GCC_TC_VER has been set either externally or to "custom"
+      # in case USE_CUSTOM_GCC_TC was set.
+      return
+   fi
 
    case $1 in
       6.4.0) ARCH_GCC_TC_VER="stable-2018.02-2"; ARCH_GCC_TC_EXT="tar.bz2";;
@@ -122,4 +146,72 @@ function dump_build_toolchain_env {
    echo "CC=$CC"
    echo "CXX=$CXX"
    echo
+}
+
+function set_gcc_ver {
+
+   if [[ "$GCC_TC_VER" == "" ]]; then
+
+      if [ -f $TC/.gcc_tc_ver_$ARCH ]; then
+
+         GCC_TC_VER=$(cat $TC/.gcc_tc_ver_$ARCH)
+
+      else
+
+         # GCC_TC_VER is not defined and there is no .gcc_tc_ver_$ARCH file.
+
+         if [[ "$USE_CUSTOM_GCC_TC" == 1 ]]; then
+            GCC_TC_VER=$CUSTOM_GCC_TC_VERSION    # Custom GCC toolchain
+         elif [[ "$HOST_ARCH" == "$BUILD_ARCH" ]]; then
+            GCC_TC_VER="$DEFAULT_GCC_TC_VERSION" # Main case, fully supported
+         fi
+      fi
+   fi
+
+   if [[ "$GCC_TC_VER" == "" ]]; then
+      echo "ERROR: GCC_TC_VER is not set"
+      exit 1
+   fi
+}
+
+function set_gcc_tc_defaults {
+
+   # Default GCC toolchain version to use. Unfortunately, it depends on the
+   # target # architecture, because the list of available pre-built toolchains
+   # on https://toolchains.bootlin.com depends on the architecture.
+
+   if ! [ -f $GCC_TC_CONF/$ARCH/default_ver ]; then
+      echo "ERROR: file $GCC_TC_CONF/$ARCH/default_ver not found"
+      exit 1
+   fi
+
+   DEFAULT_GCC_TC_VERSION=$(cat $GCC_TC_CONF/$ARCH/default_ver)
+   MIN_GCC_TC_VERSION=$(cat $GCC_TC_CONF/$ARCH/min_ver)
+
+   # Custom GCC toolchain from https://github.com/vvaltchev/musl-cross-make
+   # TODO: add a per-arch configuration file for this toolchain as well.
+   CUSTOM_GCC_TC_VERSION="11.4.0"
+}
+
+function save_and_check_gcc_tc_ver {
+
+   if ! [ -f $TC/.gcc_tc_ver_$ARCH ]; then
+
+      mkdir -p $TC
+      echo -n $GCC_TC_VER > $TC/.gcc_tc_ver_$ARCH
+
+   else
+
+      saved=$(cat $TC/.gcc_tc_ver_$ARCH)
+      v=$GCC_TC_VER
+
+      if ! [ "$GCC_TC_VER" = "$saved" ]; then
+         echo "ERROR: GCC_TC_VER ($v) does not match with saved one ($saved)"
+         echo "ERROR: This is NOT a supported scenario. Please delete:"
+         echo "   $TC/$ARCH"
+         echo "   $TC/.gcc_tc_ver_$ARCH"
+         echo "And run this script again to use the new toolchain."
+         exit 1
+      fi
+   fi
 }
