[scripts] Move set_host_arch_variable() to script_utils

diff --git a/scripts/bash_includes/script_utils b/scripts/bash_includes/script_utils
--- a/scripts/bash_includes/script_utils
+++ b/scripts/bash_includes/script_utils
@@ -83,6 +83,35 @@ fi
 ############################################
 # FUNCTIONS
 
+function set_host_arch_variable {
+
+   HOST_ARCH="`uname -m`"
+
+   if [[ "$HOST_ARCH" == "x86_64" ]]; then
+
+      : # Great, that's our DEFAULT host architecture: do nothing
+
+   elif [[ "$HOST_ARCH" == "amd64" ]]; then
+
+      # An alias for x86_64: fix our variable
+      HOST_ARCH="x86_64"
+
+   elif [[ "$HOST_ARCH" == "aarch64" ]]; then
+
+      : # That's OK: no translation necessary.
+
+   elif [[ "$HOST_ARCH" == "arm64" ]]; then
+
+      HOST_ARCH="aarch64"
+
+   else
+
+      echo "ERROR: build host architecture $HOST_ARCH not supported"
+      exit 1
+   fi
+}
+
+
 # $1 version in the format "major.minor.patchlevel"
 # $2 component number to get (1 => major, 2 => minor, 3 => patchlevel)
 function get_version_comp {
