[toolchain] Drop hacks for the old $TC/.gcc_tc_ver file [breaking change]
Almost two years ago, with commit d5ed4698793, the $TC/.gcc_tc_ver file
was renamed to $TC/.gcc_tc_ver_$ARCH because it turned out that we cannot
assume the same version of the toolchain could be even available for all
the architectures. To support going back and forth between builds and to
support the older Docker containers for testing, a few hacks were added
in both CMakeLists.txt and in the build_toolchain script. The idea was to
remove those hacks once the we migrate to an even better directory structure
for the toolchain, called v3. However, because of how easy is to actually
share the toolchain cache, re-working the toolchain into an even better
structure turned out to be not a priority for the project, despite now 3
architectures are supported.

Therefore, to keep the code at bit cleaner, this change drops those hacks,
with the assumption that building a 2 year old version of Tilck will now
require manually adding that .gcc_tc_ver file back to the toolchain2
directory, if the developer wants to reuse the toolchain2.

Considering that will almost never be the case, because multiple things
changed in the project already (min version for CMake, min version for GCC),
it seems the trade-off in favor of simplification is the right one in this
case.

diff --git a/scripts/build_toolchain b/scripts/build_toolchain
--- a/scripts/build_toolchain
+++ b/scripts/build_toolchain
@@ -88,34 +88,16 @@ fi
 # ARCH and ARCH_* variables are all about the TARGET architecture
 
 if [ -z "$GCC_TC_VER" ]; then
-
    if [ -f $TC/.gcc_tc_ver_$ARCH ]; then
-
       GCC_TC_VER=$(cat $TC/.gcc_tc_ver_$ARCH)
-
    else
-
-      if [ -f $TC/.gcc_tc_ver ]; then
-
-         # TODO: drop this once we upgrade to toolchain3
-
-         if [[ "$ARCH" == "i386" ]]; then
-            # Small hack to support older toolchains
-            GCC_TC_VER=$(cat $TC/.gcc_tc_ver)
-         fi
-
-         # Upgrade the toolchain to the latest format
-         if [[ "$RUNNING_IN_CI" != "1" ]]; then
-
-            # Keep the old .gcc_tc_ver file to support building older commits
-            cp $TC/.gcc_tc_ver $TC/.gcc_tc_ver_i386
-         fi
-      fi
+      GCC_TC_VER="$DEFAULT_GCC_TC_VERSION"
    fi
 fi
 
 if [ -z "$GCC_TC_VER" ]; then
-   GCC_TC_VER="$DEFAULT_GCC_TC_VERSION"
+   echo "ERROR: GCC_TC_VER is not set"
+   exit 1
 fi
 
 #
