[scripts] Don't allow running build_toolchain -s if $TC does not exist

diff --git a/scripts/build_toolchain b/scripts/build_toolchain
--- a/scripts/build_toolchain
+++ b/scripts/build_toolchain
@@ -130,6 +130,7 @@ MUSL_INSTALL=$TC/$ARCH/musl/install
 
 echo
 echo "ARCH=$ARCH"
+echo "HOST_ARCH=$HOST_ARCH"
 echo "GCC_TC_VER=$GCC_TC_VER"
 echo "ARCH_GCC_TC_VER=$ARCH_GCC_TC_VER"
 echo
@@ -434,6 +435,21 @@ function main {
       export PATH="$GCC_TOOLCHAIN:$PATH"
    fi
 
+
+   if [ "$1" == "-s" ] && ! [ -d $TC/$ARCH ]; then
+
+      echo
+      echo "ERROR: directory $TC/$ARCH not found."
+      echo
+      echo "It is necessary to run this script *without* options first to "
+      echo "download and build a minimum toolchain. Then, it will be possible"
+      echo "to download and build the extra packages."
+      echo
+      echo "For more info: "
+      echo "   https://github.com/vvaltchev/tilck/blob/master/docs/building.md"
+
+      exit 1
+   fi
 
    mkdir -p $TC
    mkdir -p $TC/cache
