[toolchain] Drop support for full func names in favor of package names

diff --git a/scripts/build_toolchain b/scripts/build_toolchain
--- a/scripts/build_toolchain
+++ b/scripts/build_toolchain
@@ -70,9 +70,10 @@ dump_build_toolchain_env
 
 function print_func {
 
-   local fname="$1"
-   local has_printf="$2"
-   local is_default="$3"
+   local ftype="$1"
+   local fname="$2"
+   local has_printf="$3"
+   local is_default="$4"
    local def=""
 
    if [[ $is_default = 1 ]]; then
@@ -83,7 +84,7 @@ function print_func {
 
       local attrs=""
       local extra_info=""
-      local installed_func="${fname}_installed_status"
+      local installed_func="${ftype}_${fname}_installed_status"
 
       if [[ "$(type -t $installed_func)" == 'function' ]]; then
 
@@ -140,28 +141,18 @@ function show_help {
 
    echo ""
    echo "Syntax:"
-   echo "      $0 [-n]                             run default functions"
-   echo "      $0 -s func1 [func2 [func3 [...]]]   run specific functions"
-   echo ""
+   echo "      $0 [-n]                           install only default packages"
+   echo "      $0 -s, install <pkg1> [pkg2...]   download/build/install pkgs"
+   echo "      $0 -c, config <pkg>               (re)configure a specific pkg"
+   echo
    echo "   -n        Do not check nor install system packages (advanced)"
-   echo "                Even if many packages are downloaded & built by this"
-   echo "                script without touching the system, some packages are"
-   echo "                required to be installed in the system. For example: "
-   echo "                wget, git, make, binutils, bzip2, rpmextract and "
-   echo "                others similar. When -n is NOT passed, the script "
-   echo "                first tries to detect the current Linux distribution "
-   echo "                and then it checks if all the required packages are "
-   echo "                already installed. In case some packages need to be "
-   echo "                installed, this script will show a list and run: "
-   echo "                    sudo <package manager> install [pkg1 [pkg2 ...]]"
-   echo "                In case the user does not want this script to install "
-   echo "                the necessary packages he/she could just interrupt "
-   echo "                this script with Ctrl+C, without affecting the "
-   echo "                system."
+   echo "                Do not check for nor attempt to install any of the"
+   echo "                mandatory system packages like: wget, git, make, "
+   echo "                binutils, bzip2, rpmextract, etc."
    echo
    echo "   --clean   Remove everything from the toolchain, except the cache"
    echo ""
-   echo "Functions supported by this script (with -s):"
+   echo "--- Packages for the current arch/host_arch configuration ---"
    echo ""
 
    local has_printf=0
@@ -172,36 +163,49 @@ function show_help {
    fi
 
    for x in ${default_funcs[@]}; do
-      print_func "$x" $has_printf 1
+
+      if [[ $x =~ (download|build|config)_(.+) ]]; then
+
+         local t=${BASH_REMATCH[1]}
+         local n=${BASH_REMATCH[2]}
+
+         print_func $t $n $has_printf 1
+      fi
    done
 
    for x in ${all_funcs_list[@]}; do
 
       if [[ "$all_def_funcs" =~ " ${x} " ]]; then
-         continue 2
+         # already included by the default funcs, skip
+         continue
       fi
 
-      # Skip the config_* functions, in order to print them last
-      if [[ "$x" =~ config_* ]]; then
-         continue 2
-      fi
+      if [[ $x =~ (download|build|config)_(.+) ]]; then
 
-      print_func "$x" $has_printf 0
-   done
+         local t=${BASH_REMATCH[1]}
+         local n=${BASH_REMATCH[2]}
 
-   # Now print all the config_* funcs
-   for x in ${all_funcs_list[@]}; do
-      if [[ "$x" =~ config_* ]]; then
-         print_func "$x" $has_printf 0
+         if [[ t == "config" ]]; then
+            # Skip the config_* functions. We'll print them separately.
+            continue
+         fi
+
+         print_func $t $n $has_printf 0
       fi
    done
 
    echo ""
-   echo -e "(*) Functions ran by default\n"
-}
+   echo -e "(*) Installed by default (in $TC)\n"
+   echo ""
+   echo "--- Config functions ---"
 
-function show_error_no_func {
-   echo "ERROR: The function '$1' does not exist. Re-run with --help."
+   # Now print all the config_* funcs
+   for x in ${all_funcs_list[@]}; do
+      if [[ "$x" =~ config_(.+) ]]; then
+         print_func config "${BASH_REMATCH[1]}" $has_printf 0
+      fi
+   done
+   echo ""
 }
 
 function execute_func {
@@ -220,21 +224,6 @@ function execute_func {
    fi
 }
 
-function check_func {
-
-   local func="$1"
-
-   for x in ${all_funcs_list[@]}; do
-      if [[ "$x" == "$func" ||
-            "$x" == "build_$func" ||
-            "$x" == "download_$func" ]]
-      then
-         return 0
-      fi
-   done
-
-   return 1 # Function not found
-}
 
 function perform_full_clean {
 
@@ -348,20 +337,8 @@ function main {
       unset ha
    fi
 
-
-   if [ "$1" == "-s" ] && ! [ -d $TC/$ARCH ]; then
-
-      echo
-      echo "ERROR: directory $TC/$ARCH not found."
-      echo
-      echo "It is necessary to run this script *without* options first to "
-      echo "download and build a minimum toolchain. Then, it will be possible"
-      echo "to download and build the extra packages."
-      echo
-      echo "For more info: "
-      echo "   https://github.com/vvaltchev/tilck/blob/master/docs/building.md"
-
-      exit 1
+   if ! [ -d $TC/$ARCH ]; then
+      local no_arch_directory=1
    fi
 
    mkdir -p $TC
@@ -388,28 +365,62 @@ function main {
    fi
 
 
-   if [[ "$1" == "-s" ]]; then
+   if [[ "$1" == "-s" || "$1" == "install" ||
+         "$1" == "-c" || "$1" == "config"
+      ]]
+   then
+
+      local cmd="$1"
+      if [[ "$1" == "-s" ]]; then
+         cmd="install"
+      elif [[ "$1" == "-c" ]]; then
+         cmd="config"
+      fi
 
       if [[ $# < 2 ]]; then
-         echo "Expected the name of the function to call after the $1 option"
+         echo "Expected argument after '$1'"
+         exit 1
+      fi
+
+      if [[ "$no_arch_directory" == 1 ]]; then
+         echo
+         echo "ERROR: directory $TC/$ARCH not found."
+         echo
+         echo "It is necessary to run this script *without* options first to "
+         echo "download and build a minimum toolchain. Then, it will be possible"
+         echo "to download and build the extra packages."
+         echo
+         echo "For more info, see: docs/building.md"
+         echo
+         rm -rf $TC/$ARCH
+         exit 1
       fi
 
       shift  # Drop the first argument, $1
 
       for func in "$@"; do
 
-         if ! check_func "$func"; then
-            show_error_no_func "$func"
-            exit 1
-         fi
+         if [[ $cmd == install ]]; then
 
-         if ! execute_func $func; then
+            # Try build_ and download_
             if ! execute_func "build_$func"; then
                if ! execute_func "download_$func"; then
-                  show_error_no_func "$func"
+                  echo "ERROR: unknown package '$func'"
                   exit 1
                fi
             fi
+
+         elif [[ $cmd == config ]]; then
+
+            # Try only config_
+            if ! execute_func "config_$func"; then
+               echo "ERROR: unknown config func '$func'"
+               exit 1
+            fi
+
+            # In case of success, break from the loop. Don't allow to
+            # reconfigure multiple packages at the same time.
+            break
          fi
 
       done
