[build_toolchain] Introduce the function build_micropython

diff --git a/scripts/build_toolchain b/scripts/build_toolchain
--- a/scripts/build_toolchain
+++ b/scripts/build_toolchain
@@ -634,6 +634,55 @@ function build_tcc {
    popd
 }
 
+all_funcs_list+=(build_micropython)
+function build_micropython {
+
+   pushd .
+
+   if ! [ -d micropython ]; then
+
+      show_work_on_component_msg "MICROPYTHON"
+
+      git clone --depth 1 https://github.com/micropython/micropython.git
+      cd micropython
+
+      if [[ "$HOST_ARCH" != "$BUILD_ARCH" ]]; then
+
+         # Case HOST_ARCH == ARCH
+         # Note: if HOST_ARCH not in [BUILD_ARCH, ARCH], we fail earlier.
+         #
+         # Note: NOT TESTED yet.
+         # Remember: this scenario (building on $ARCH) is _not_ officially
+         # supported.
+
+         export SYS_CC="$CC"
+         export SYS_CXX="$CXX"
+         export CC_POST_FLAGS="-specs $TC/musl/install/lib/musl-gcc.specs"
+      fi
+
+      export CROSS_COMPILE="${ARCH_GCC_TC}-linux-"
+      export LDFLAGS_EXTRA="-static"
+
+      pushd mpy-cross
+      run_command2 "make MICROPY_PY_FFI=0 -j" build.log
+      popd
+
+      pushd ports/unix
+      run_command2 "make submodules" make_submodules.log
+      run_command2 "make MICROPY_PY_FFI=0 -j" build.log
+      popd
+
+      export LDFLAGS_EXTRA=""
+      export CROSS_COMPILE=""
+
+   else
+      show_skip_component_msg "MICROPYTHON"
+   fi
+
+   popd
+}
+
+
 function arch_checks {
 
    if [[ "$HOST_ARCH" != *"$BUILD_ARCH"* ]]; then
