[build] Going back: support older compilers up to gcc 4.8

diff --git a/scripts/cmake_run b/scripts/cmake_run
--- a/scripts/cmake_run
+++ b/scripts/cmake_run
@@ -49,15 +49,28 @@ echo "gcc version: $cc_ver"
 echo "g++ version: $cxx_ver"
 
 cc_major=`echo -ne $cc_ver | grep -Eo '[0-9]+' | head -1`
-cxx_major=`echo -ne $cxx_ver | grep -Eo '[0-9]+' | head -1`
+cc_minor=`echo -ne $cc_ver | grep -Eo '[0-9]+' | head -2 | tail -1`
 
-if [ $cc_major -lt 5 ]; then
-   echo "Your gcc compiler is too old. Version >= 5 is required."
+cxx_major=`echo -ne $cxx_ver | grep -Eo '[0-9]+' | head -1`
+cxx_minor=`echo -ne $cxx_ver | grep -Eo '[0-9]+' | head -2 | tail -1`
+
+if [ $cc_major -lt 4 ]; then
+   echo "Your gcc compiler is too old. Version >= 4.8 is required."
    exit 1
 fi
 
-if [ $cxx_major -lt 5 ]; then
-   echo "Your g++ compiler is too old. Version >= 5 is required."
+if [ $cxx_major -lt 4 ]; then
+   echo "Your g++ compiler is too old. Version >= 4.8 is required."
+   exit 1
+fi
+
+if [ $cc_minor -lt 8 ]; then
+   echo "Your gcc compiler is too old. Version >= 4.8 is required."
+   exit 1
+fi
+
+if [ $cxx_minor -lt 8 ]; then
+   echo "Your g++ compiler is too old. Version >= 4.8 is required."
    exit 1
 fi
 
