[toolchain] Fix support for USE_SYSCC=1 on HOST_ARCH=x86_64
This change fixes the broken support for USE_SYSCC=1. This rarely-used option
gives us two features:

   - building the kernel with the system compiler, which can also be clang
     and benefit from extra checks & warnings

   - building the user apps with the our custom libmusl instead of one the
     one included in the pre-built toolchain. The advantage of that is having
     the debug symbols in case of low-level libc issues to debug.

Building the user apps entirely with the system compiler is not part of the
goals of this feature and not only isn't very useful as a feature unless
$ARCH == $HOST_ARCH, but it's extremely hard to make it work, because of the
libmusl. Cross-compiling to from x86-64 to i386 when gcc-multlib is installed
is simple with the -m32 option, but doing so while also changing the libc
to libmusl opens several nastly problems, because when we pass the libmusl
specs to the system compiler, somehow at least for BusyBox the 64-bit system
linker (ld) ends up being called, instead of the 32-bit system linker, which
typically is /lib32/ld-linux.so.2.

Therefore, since we're supporting USE_SYSCC=1 only for the two features above,
we solve this problem with an ugly hack: use the GCC cross-compiler from the
toolchain, which by default links to the target ARCH and change the libc
using the musl specs from our custom libmusl build.

Over the time, this feature has been broken for multiple reasons, when changes
have been made to fix one use-case (e.g. ARCH == HOST_ARCH or ARCH == x86_64
or HOST_ARCH == aarch64) forgetting about the undesired side-effects for the
rest of the use cases.

Recently, commit 37a1b27a7 completely broke the build of USE_SYSCC=1 in the
most important use-cases, when HOST_ARCH == x86_64 and ARCH == i386. This
change hopefully fixes most of not all of the issues related with this feature
in one big change.

In addition to that, this change makes the diagnosis of ugly build failures of
user apps easier, by writing to the build.log file in each package a fair
amount of debug data related to the environment variables.

diff --git a/scripts/tc/pkgs/busybox b/scripts/tc/pkgs/busybox
--- a/scripts/tc/pkgs/busybox
+++ b/scripts/tc/pkgs/busybox
@@ -10,21 +10,19 @@ function internal_build_busybox {
 
    cp $MAIN_DIR/other/busybox.config .config
 
-   if [[ "$USE_SYSCC" == 1 ]]; then
-
-      export SYS_CC="$CC"
-      export SYS_CXX="$CXX"
-      export CC_POST_FLAGS="-specs $MUSL_INSTALL/lib/musl-gcc.specs"
-
-   else
-
-      # Default case
-      set_cc_vars_to_tc
-   fi
-
+   do_common_cross_compiler_setup
+   set_cc_vars_to_tc
    export CROSS_COMPILE="${ARCH_GCC_TC}-linux-"
-   run_command2 "make -j$BUILD_PAR" build.log
 
+   set +e
+   run_command2 "make V=1 -j$BUILD_PAR" build.log
+   dump_cross_compiler_env "build.log"
+
+   if ! [ -f $TC/$ARCH/busybox/busybox ]; then
+      echo "ERROR: build failed !!!" >> build.log
+      exit 1
+   fi
+   set -e
    export CROSS_COMPILE=""
    export CC_POST_FLAGS=""
 
diff --git a/scripts/tc/pkgs/fbdoom b/scripts/tc/pkgs/fbdoom
--- a/scripts/tc/pkgs/fbdoom
+++ b/scripts/tc/pkgs/fbdoom
@@ -95,26 +95,22 @@ function build_fbdoom {
       download_fbdoom
       cd fbDOOM
 
-      if [[ "$USE_SYSCC" == 1 ]]; then
-
-         # Note: NOT TESTED yet.
-         # Remember: this scenario (building on $ARCH) is _not_ officially
-         # supported.
-
-         export SYS_CC="$CC"
-         export SYS_CXX="$CXX"
-         export CC_POST_FLAGS="-specs $MUSL_INSTALL/lib/musl-gcc.specs"
-
-      else
-         # Default case
-         set_cc_vars_to_tc
-      fi
-
+      do_common_cross_compiler_setup
+      set_cc_vars_to_tc
       export CROSS_COMPILE="${ARCH_GCC_TC}-linux-"
       export LDFLAGS="-static"
 
       pushd fbdoom
+      set +e
       run_command2 "make NOSDL=1 -j$BUILD_PAR" build.log
+      dump_cross_compiler_env "build.log"
+
+      if ! [ -f fbdoom ]; then
+         echo "ERROR: build failed !!!" >> build.log
+         exit 1
+      fi
+
+      set -e
       ${ARCH_GCC_TC}-linux-strip --strip-all fbdoom
       gzip fbdoom
       popd
diff --git a/scripts/tc/pkgs/micropython b/scripts/tc/pkgs/micropython
--- a/scripts/tc/pkgs/micropython
+++ b/scripts/tc/pkgs/micropython
@@ -35,36 +35,32 @@ function build_micropython {
       cd micropython
 
       if [[ "$USE_SYSCC" == 1 ]]; then
-
-         # Case HOST_ARCH == ARCH
-         # Note: if HOST_ARCH not in [BUILD_ARCH, ARCH], we fail earlier.
-         #
-         # Note: NOT TESTED yet.
-         # Remember: this scenario (building on $ARCH) is _not_ officially
-         # supported.
-
-         export SYS_CC="$CC"
-         export SYS_CXX="$CXX"
-         export CC_POST_FLAGS="-specs $MUSL_INSTALL/lib/musl-gcc.specs"
-
-      else
-
-         # Default case
-         set_cc_vars_to_tc
-         export CROSS_COMPILE="${ARCH_GCC_TC}-linux-"
+         echo "ERROR: micropython doesn't support USE_SYSCC=1 at the moment"
+         exit 1
       fi
 
+      set_cc_vars_to_tc
+      export CROSS_COMPILE="${ARCH_GCC_TC}-linux-"
       export LDFLAGS_EXTRA="-static"
-      local opts="MICROPY_PY_FFI=0 MICROPY_PY_THREAD=0"
+      local opts="V=1 MICROPY_PY_FFI=0 MICROPY_PY_THREAD=0"
 
+      set +e
       pushd mpy-cross
-      run_command2 "make $opts -j$BUILD_PAR" build.log
+      run_command2 "make $opts -j$BUILD_PAR" build_1.log
+      dump_cross_compiler_env "build_1.log"
       popd
 
       pushd ports/unix
       run_command2 "make submodules" make_submodules.log
-      run_command2 "make $opts -j$BUILD_PAR" build.log
+      run_command2 "make $opts -j$BUILD_PAR" build_2.log
+      dump_cross_compiler_env "build_2.log"
+
+      if ! [ -f $TC/$ARCH/micropython/ports/unix/micropython ]; then
+         echo "ERROR: build failed !!!" >> build_2.log
+         exit 1
+      fi
       popd
+      set -e
 
       export LDFLAGS_EXTRA=""
       export CROSS_COMPILE=""
diff --git a/scripts/tc/pkgs/tcc b/scripts/tc/pkgs/tcc
--- a/scripts/tc/pkgs/tcc
+++ b/scripts/tc/pkgs/tcc
@@ -32,11 +32,7 @@ function build_tcc {
          install_32bit_libs
       fi
 
-      # Download the gcc toolchain even in the case HOST != BUILD_ARCH
-      # because we'll need its sysroot to be deployed in Tilck's image.
-      DOWNLOAD_IGNORING_SYSCC="1"
       download_gcc_toolchain
-      DOWNLOAD_IGNORING_SYSCC=""
    fi
 
 
@@ -66,8 +62,13 @@ function build_tcc {
 
       if [[ "$USE_SYSCC" == 1 ]]; then
 
-         export SYS_CC="$CC"
-         export SYS_CXX="$CXX"
+         if [[ "$HOST_ARCH" == "$ARCH" ]]; then
+            export SYS_CC="$CC"
+            export SYS_CXX="$CXX"
+         else
+            export SYS_CC="$GCC_TOOLCHAIN/${ARCH_GCC_TC}-linux-gcc"
+            export SYS_CXX="$GCC_TOOLCHAIN/${ARCH_GCC_TC}-linux-g++"
+         fi
          export CC_POST_FLAGS="-specs $MUSL_INSTALL/lib/musl-gcc.specs"
 
          # Hack: unfortunately, while tcc's build system uses the
@@ -112,8 +113,17 @@ function build_tcc {
       fi
 
       run_command2 "./configure $af" configure.log
-      run_command2 "make $make_vars cross-$ARCH" build.log
 
+      set +e
+      run_command2 "make $make_vars cross-$ARCH" build.log
+      dump_cross_compiler_env "build.log"
+
+      if ! [ -f $TC/$ARCH/tcc/${ARCH}-tcc ]; then
+         echo "ERROR: build failed !!!" >> build.log
+         exit 1
+      fi
+
+      set -e
       # Just to test on the local machine
       # run_command2 "make install" install.log
 
