[toolchain] Intr. support for the gmock library

diff --git a/scripts/tc/pkgs/gtest b/scripts/tc/pkgs/gtest
--- a/scripts/tc/pkgs/gtest
+++ b/scripts/tc/pkgs/gtest
@@ -8,6 +8,8 @@
 GTEST_VER="1.12.1"
 GTEST_DIRNAME="gtest-$GTEST_VER"
 GTEST_SRC_DIR="$TC/noarch/$GTEST_DIRNAME"
+GMOCK_DIRNAME="gmock-$GTEST_VER"
+
 
 function download_googletest {
 
@@ -81,6 +83,44 @@ function build_gtest_installed_status {
    fi
 }
 
+all_funcs_list+=(build_gmock)
+function build_gmock {
+
+   download_googletest
+   pushd host_$HOST_ARCH
+
+   if ! [ -d $GMOCK_DIRNAME ]; then
+
+      show_work_on_component_msg "GOOGLE MOCK ($HOST_ARCH)"
+      mkdir $GMOCK_DIRNAME
+      cd $GMOCK_DIRNAME
+
+      reset_cc_vars
+
+      $CMAKE                              \
+         -DCMAKE_BUILD_TYPE=Debug         \
+         -DGOOGLETEST_VERSION=$GTEST_VER  \
+         $GTEST_SRC_DIR/googlemock
+
+      run_command2 "make -j$BUILD_PAR" build.log
+
+   else
+      show_skip_component_msg "GOOGLE MOCK ($HOST_ARCH)"
+   fi
+
+   popd
+}
+
+function build_gmock_installed_status {
+   if [ -d $TC/host_$HOST_ARCH/$GMOCK_DIRNAME ]; then
+      if [ -f $TC/host_$HOST_ARCH/$GMOCK_DIRNAME/lib/libgmock.a ]; then
+         echo "installed host_$HOST_ARCH"
+      else
+         echo "error"
+      fi
+   fi
+}
+
 all_funcs_list+=(build_gtest_arch)
 function build_gtest_arch {
 
@@ -126,6 +166,59 @@ function build_gtest_arch {
 function build_gtest_arch_installed_status {
    if [ -d $TC/host_$ARCH/$GTEST_DIRNAME ]; then
       if [ -f $TC/host_$ARCH/$GTEST_DIRNAME/lib/libgtest.a ]; then
+         echo "installed host_$ARCH"
+      else
+         echo "failed"
+      fi
+   fi
+}
+
+
+all_funcs_list+=(build_gmock_arch)
+function build_gmock_arch {
+
+   download_googletest
+   pushd host_$ARCH
+
+   if ! [ -d $GMOCK_DIRNAME ]; then
+
+      show_work_on_component_msg "GOOGLE TEST ($ARCH)"
+      download_gcc_glibc_toolchain
+
+      # We have to save the current path and prepend the GLIBC toolchain
+      # to it, because we're targeting the host system.
+
+      local saved_path="$PATH"
+      export PATH="$GCC_TOOLCHAIN_GLIBC:$PATH"
+
+      mkdir $GMOCK_DIRNAME
+      cd $GMOCK_DIRNAME
+
+      # After this, we'll use the $GCC_TOOLCHAIN_GLIBC toolchain, which is
+      # a cross-toolchain, but uses glibc.
+      set_cc_vars_to_tc
+
+      $CMAKE                              \
+         -DCMAKE_BUILD_TYPE=Debug         \
+         -DGOOGLETEST_VERSION=$GTEST_VER  \
+         $GTEST_SRC_DIR/googlemock
+
+      run_command2 "make -j" build.log
+
+      # Restore the PATH so that other functions will end up calling the musl
+      # toolchain with $ARCH-linux-gcc.
+      export PATH="$saved_path"
+
+   else
+      show_skip_component_msg "GOOGLE TEST ($ARCH)"
+   fi
+
+   popd
+}
+
+function build_gmock_arch_installed_status {
+   if [ -d $TC/host_$ARCH/$GMOCK_DIRNAME ]; then
+      if [ -f $TC/host_$ARCH/$GMOCK_DIRNAME/lib/libgmock.a ]; then
          echo "installed host_$ARCH"
       else
          echo "failed"
