[toolchain] Fix support for USE_SYSCC=1 on HOST_ARCH=x86_64
This change fixes the broken support for USE_SYSCC=1. This rarely-used option
gives us two features:

   - building the kernel with the system compiler, which can also be clang
     and benefit from extra checks & warnings

   - building the user apps with the our custom libmusl instead of one the
     one included in the pre-built toolchain. The advantage of that is having
     the debug symbols in case of low-level libc issues to debug.

Building the user apps entirely with the system compiler is not part of the
goals of this feature and not only isn't very useful as a feature unless
$ARCH == $HOST_ARCH, but it's extremely hard to make it work, because of the
libmusl. Cross-compiling to from x86-64 to i386 when gcc-multlib is installed
is simple with the -m32 option, but doing so while also changing the libc
to libmusl opens several nastly problems, because when we pass the libmusl
specs to the system compiler, somehow at least for BusyBox the 64-bit system
linker (ld) ends up being called, instead of the 32-bit system linker, which
typically is /lib32/ld-linux.so.2.

Therefore, since we're supporting USE_SYSCC=1 only for the two features above,
we solve this problem with an ugly hack: use the GCC cross-compiler from the
toolchain, which by default links to the target ARCH and change the libc
using the musl specs from our custom libmusl build.

Over the time, this feature has been broken for multiple reasons, when changes
have been made to fix one use-case (e.g. ARCH == HOST_ARCH or ARCH == x86_64
or HOST_ARCH == aarch64) forgetting about the undesired side-effects for the
rest of the use cases.

Recently, commit 37a1b27a7 completely broke the build of USE_SYSCC=1 in the
most important use-cases, when HOST_ARCH == x86_64 and ARCH == i386. This
change hopefully fixes most of not all of the issues related with this feature
in one big change.

In addition to that, this change makes the diagnosis of ugly build failures of
user apps easier, by writing to the build.log file in each package a fair
amount of debug data related to the environment variables.

diff --git a/scripts/tc/pkgs/ncurses b/scripts/tc/pkgs/ncurses
--- a/scripts/tc/pkgs/ncurses
+++ b/scripts/tc/pkgs/ncurses
@@ -27,17 +27,21 @@ function build_ncurses {
       local o4="--without-progs --without-cxx --without-cxx-binding"
       local o5="--without-ada --without-manpages --without-dlsym"
 
-      if [[ "$USE_SYSCC" == 1 ]]; then
-         export SYS_CC="$CC"
-         export SYS_CXX="$CXX"
-         export CC_POST_FLAGS="-specs $MUSL_INSTALL/lib/musl-gcc.specs"
-      else
-         set_cc_vars_to_tc
-      fi
-
+      do_common_cross_compiler_setup
+      set_cc_vars_to_tc
       run_command2 "./configure $o1 $o2 $o3 $o4 $o5" configure.log
+
+      set +e
       run_command2 "make -j$BUILD_PAR" build.log
       run_command2 "make install" install.log
+      dump_cross_compiler_env "build.log"
+
+      if ! [ -f $TC/$ARCH/ncurses/install/lib/libncurses.a ]; then
+         echo "ERROR: build failed !!!" >> build.log
+         exit 1
+      fi
+
+      set -e
       export CC_POST_FLAGS=""
 
    else
diff --git a/scripts/tc/pkgs/vim b/scripts/tc/pkgs/vim
--- a/scripts/tc/pkgs/vim
+++ b/scripts/tc/pkgs/vim
@@ -49,32 +49,26 @@ function build_vim {
 
       local curr="$PWD"
 
-      if [[ "$USE_SYSCC" == 1 ]]; then
-
-         # Remember: this scenario (building on $ARCH) is _not_ officially
-         # supported.
-
-         export SYS_CC="$CC"
-         export SYS_CXX="$CXX"
-         export CC_POST_FLAGS="-specs $MUSL_INSTALL/lib/musl-gcc.specs"
-
-         export CC="$MAIN_DIR/scripts/build_scripts/${ARCH}-gcc"
-         export CXX="$MAIN_DIR/scripts/build_scripts/${ARCH}-g++"
-
-      else
-
-         # Default case
-         set_cc_vars_to_tc
-      fi
-
+      do_common_cross_compiler_setup
+      set_cc_vars_to_tc
       export CFLAGS="-ggdb -Os"
       export LDFLAGS="-static -L$ncurses/lib"
       export CPPFLAGS="-I$ncurses/include/ncurses"
 
       local c_opts="--with-features=normal"
       run_command2 "./configure --prefix=$curr/install $c_opts" configure.log
+
+      set +e
       run_command2 "make -j$BUILD_PAR" build.log
       run_command2 "make install" install.log
+      dump_cross_compiler_env "build.log"
+
+      if ! [ -f install/bin/vim ]; then
+         echo "ERROR: build failed !!!" >> build.log
+         exit 1
+      fi
+
+      set -e
 
       pushd install
 
@@ -90,6 +84,11 @@ function build_vim {
          gzip -c --best ./bin/vim > vim.gz
          chmod 644 vim.gz
       popd
+
+      if ! [ -f $TC/$ARCH/vim/install/vim.gz ]; then
+         echo "ERROR: the install failed !!!" >> install.log
+         exit 1
+      fi
 
       export CFLAGS=""
       export LDFLAGS=""
