[LSP] Add arch allow list param to clangd-run-all-files

diff --git a/scripts/dev/clangd-run-all-files b/scripts/dev/clangd-run-all-files
--- a/scripts/dev/clangd-run-all-files
+++ b/scripts/dev/clangd-run-all-files
@@ -4,6 +4,7 @@
 SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 MAIN_DIR="$(realpath "$(cd "$SOURCE_DIR/../.." && pwd)")"
 CMDS=$MAIN_DIR/build/compile_commands.json
+ARCH_LIST=
 
 if ! [ -f $CMDS ]; then
    echo "ERROR: compile_commands.json not found"
@@ -14,6 +15,13 @@ if ! [ -f $SOURCE_DIR/clangd-check-single-file ]; then
    echo "ERROR: clangd-check-single-file not found"
    exit 1
 fi
+
+if [[ "$1" == "" ]]; then
+   echo "ERROR: missing <allowed arch list> parameters"
+   exit 1
+fi
+
+ARCH_LIST="$*"
 
 cd $MAIN_DIR
 files_list=()
@@ -38,18 +46,31 @@ for file in "${files_list[@]}"; do
    if [[ "$rp" == $MAIN_DIR/config/*.h ]]; then
       # Config files are templates processed by CMake. They contain invalid
       # directives like #cmakedefine01. Skip.
+      i=$((i+1))
       continue
    fi
 
    if [[ "$rp" == $MAIN_DIR/tests/* ]]; then
       # Unit test files are not supported, yet.
+      i=$((i+1))
       continue
    fi
 
    if [[ $file == */tfblib/fonts/*.c ]]; then
       # Font files encoded in C files take a long time to be processed by
       # clangd, let's skip them.
+      i=$((i+1))
       continue
+   fi
+
+   r='(kernel\/arch|common\/arch|modules\/[^\/]+)\/([^\/]+)\/.+'
+   if [[ "$file" =~ $r ]]; then
+      file_arch=${BASH_REMATCH[2]}
+      if ! [[ "$ARCH_LIST" == *"$file_arch"* ]]; then
+         echo "[$((i*100/count))%] SKIP: $file [Arch: $file_arch]"
+         i=$((i+1))
+         continue
+      fi
    fi
 
    echo "[$((i*100/count))%] FILE: $file"
